### PR TITLE
Image background

### PR DESCRIPTION
**Pull request by erangre**
Two modifications for image background.
1. An added button for optional showing of the subtracted image in the image view.
2. A new batch mode for auto saving images (useful for saving background subtracted images). Currently saves in the same folder with "batch_" added before the filename.

### CODE REVIEW

**Comment by CPrescher** [comment]
Hi,

thx for this. I like it, however I would like to add some things:

1. the BG button should only appear if there is any background loaded, it probably should also be spelled "bg" as in the pattern graph.

2. I think the batch-image output should ask everytime for a folder (it could use the pattern as start). I think it should be separate from the pattern folder...

In general we should also think about automatic saving of cakes (as data, which needs the addition of files for each pixel azimuth and 2theta), or cake images with included axes.

**Comment by erangre** [comment]
Hi,

1. ok. will fix it.

2. I will add something to ask which folder to save into, but I think the default should be the folder with the images and not the pattern folder, since it will allow users to more browse between these images and the originals for comparison.

3. Do you mean saving a csv file of the cake data automatically for many files? I haven't encountered a situation where one needs to export the data of a large number of cakes.

**Comment by CPrescher** [comment]
Hi Eran,

I already did number 1.
I agree to your number 2.

3. you are probably right, anyways, we need an option to save the pixel coordinates:)

**Comment by CPrescher** [comment]
i will do number 2. so you can work on the other pull request.

**Pull request merged**
