### PR TITLE
Cake export

### PR DESCRIPTION
**Pull request by erangre**
Save a text file with the tth and azimuth headers and the cake data.
This is done through the save image button. Only works in cake mode (when in image mode it does nothing).

### CODE REVIEW

**Comment by CPrescher** [comment]
Thanks for the pull request.

Do you think one really needs all the data saved in a txt or csv file like implemented right now? What I was thinking is to just be able to save a file with first line giving the tth values and second line the azimuth values. Of course, this would need to be not in the "save image" button but rather on top. I wanted to start working on having different azimuth and tth ranges for the cake integration. Maybe it can be added there?

**Comment by erangre** [comment]
I am not sure.
When exporting the whole thing as text it is really simple to open it up in Origin and display it as a heat-map with the correct axes.
The drawback is that it is slow (both in saving, and in opening it there).
Maybe there is also a simple way to open it up as an image and have just the axes read from a data file. I will check it.

**Comment by CPrescher** [comment]
I still think adding the opportunity to save full txt files is good so i merged it. But I will add also the other possibility mentioned above

**Comment by erangre** [comment]
ok. I did actually try to import the cake image into origin and then manually add the axes but it is not so simple. So having the txt is a good option.
I think it is a good idea to have the option to choose the theta and azimuth range. There you can also show the start, end and step for each axis and have the option to export it.

**Pull request merged**
