### PR TITLE
WIP: Feat/scan processing

### PR DESCRIPTION
**Pull request by karnevskiy**
@CPrescher 

Suggest code introduces a new batch widget, which appears in separate window. This widget works with multiple images, which belongs to one dataset. Images may be stored in one or multiple files. Following functionality is implemented:
* Load multiple files with raw images
* Navigate across raw images
* Integrate raw images and show diffraction patterns as heatmap plot
* Show phases on heatmap plot
* Create watarfall plot using existing functionality of Dioptas.
* Store processed data in nexus, png and ascii formats
* Load processed data (nexus format). Processed data includes information about raw data used to create them.

### CODE REVIEW

**Comment by CPrescher** [comment]
Hi Misha,

some of the functional integration tests are failing on my side and on the Github continuous integration:
"test_change_view"
"test_dioptas_batch"
"test_integrate_with_parameters"
"test_load_missing_raw"

could you please have a look, what is wrong there?

**Comment by CPrescher** [comment]
The log can be found inside here ("it says 'All checks failed') and below is the link to CI details.

Otherwise you can go to the actions tab in the and see all the CI and CD github action scripts with output.

All the new batch controller tests are also failing because the "*proc*" files are not available. If you want them for the test they should be added to the repo.

Due to the new tests added, there is some memory issues on the CI script. Py.test unfortunately does not clean up all memory after each test (all the test runners seem to have problems with this), and thus, the CI script is canceled due too much memory requested. It might be necessary, to run now each controller test file in a single py.test run (and not use the automatic recognition of test files in a folder).

**Comment by CPrescher** [comment]
The controller tests still cannot run on another machine than yours, because it now wants to open a file with the following path:

'/home/karnem/workspace/Dioptas/dioptas/tests/data/lambda/testasapo1_1009_00002_m1_part00000.nxs'

Best wishes,
Clemens

**Comment by CPrescher** [comment]
Hi, I fixed some pathing issues on windows.

However, still some tests are failing. The major one is integrate. I get a dialog popup that a calibration file is needed and the test basically stops, unless I click OK, which is obviously not what should happen :) Is this different on your side?

**Comment by karnevskiy** [comment]
How do you execute tests. I am running the command: "python -m pytest -vv ." in the dedicated folder.

**Comment by CPrescher** [comment]
I run the tests within pycharm, but running them from command line gives the same errors:

e.g. python -m pytest test_BatchController.py

**Comment by karnevskiy** [comment]
platform linux -- Python 3.6.12, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
Works fine for me.

**Comment by karnevskiy** [comment]
Where can I see error messages. In github CI logs I saw only: "2020-12-11T08:38:26.8496222Z dioptas/tests/controller_tests/test_BatchController.py FFFFFFFFFFFFFFFFF [ 11%]
2020-12-11T08:38:39.1718638Z FFFFFFFFFFFF   "

**Comment by CPrescher** [comment]
Well it does not work on the CI and my environment, so it needs to be fixed...

you the integrate test runs the integrate function of the batch controller which has the following first lines:

 ```
def integrate(self):
        """
        Integrate images in the batch
        """
        if not self.model.calibration_model.is_calibrated:
            self.widget.show_error_msg("Can not integrate multiple images without calibration.")
```

in the test there is no calibration loaded, so this error message will pop up, which will stop the test execution

**Comment by CPrescher** [comment]
I stopped the latest CI script because the will run indefinetely...

**Comment by karnevskiy** [comment]
I saw two windows opened, but they are not the dialogue windows and not stopping test evaluation. Calibration should be loaded during setUp (line 357). I don't know, how to reproduce an error.

I see one error with dioptas-batch script, which is related to missing package: sharedmem from bioconda channel.

**Comment by CPrescher** [comment]
I would like to merge the branch soon.
Is there anything which speaks against this?

**Comment by karnevskiy** [comment]
Seems nothing more from my side.

**Pull request merged**
