### PR TITLE
Fix histogram changes on tab change

### PR DESCRIPTION
**Pull request by erangre**
When switching between tabs the histogram levels would change.
Now they are kept in a list in the main controller.

### CODE REVIEW

**Comment by erangre** [comment]
Actually there is still a problem.
The Calibration and Mask tabs don't have the Autoscale buttons, so they always autoscale.
So only for the Integration tab this works.

**Comment by CPrescher** [comment]
Do we want to add this autoscale button to the other tabs?

**Comment by erangre** [comment]
That might be best. And to set it that if someone changes the histogram autoscale turns off automatically.

**Comment by CPrescher** [comment]
Well, then actually the intensity scaling should be the same over all the tabs, I think. Meaning, that when you change the scaling in the integration tab and then switch to the mask tab it should be the same.

**Comment by erangre** [comment]
Maybe that is better. So that should be done with the original code.

**Comment by CPrescher** [comment]
I will leave it as is right now and see, if it really needs to be synchronized between all tabs

**Pull request merged**
