### PR TITLE
Save and load configurations

### PR DESCRIPTION
**Pull request by erangre**
Added buttons to save and load configurations (including open phases, open patterns, background and other modifications, the current image, etc...).
This required a change to the jcpds from many self parameters to a dictionary of parameters.

### CODE REVIEW

**Comment by CPrescher** [comment]
Hi,

thx, for this.
Couple of questions though:

Why is the filename has "temp" on it, after loading the configuration? Shouldn't I be able to continue browsing files?

Why some of the test/data tif files have been changed?

The travis testrunner says it cannot find ehook. maybe you forgot to commit?

Best wishes,
Clemens

**Comment by erangre** [comment]
Hi,

1. Sorry, looks like I forgot to finish a few things. I was using temp_ prefix for the files and calibration not to overwrite data. I meant to later add checks and only create the tif if the file doesn't already exist, and then to create it without the temp_ prefix.

2. Perhaps I accidentally overwrote some tif files in the test/data, I need to check.

3. I will figure out what went wrong with ehook there. I was using the exception hook because I wasn't able to test when I had errors in anything related to pyqt (the test would just abort without giving any error information). By the way, is there a way to do this without using the exception hook?

Best wishes,
Eran.

**Comment by erangre** [comment]
Still working on this. Just added some tests, but didn't write the actual code yet.

**Comment by erangre** [comment]
I removed the temp suffix from the image file name and from the calibration file (if the files exist it will read them, if not it will create them, if the directory does not exist, it will create in the temp directory).
I didn't do it for masks and for jcpds files, those are still saved in the temp directory, since those are files which you are more likely to change if working on two different computers and won't want to necessarily overwrite from one to the other.

I notice that it is failing the Travis CI on tests which are not failing locally for me at least.

There is something that should be added. to the hdf5 - a version attribute. This way, in the future if we modify which settings are saved in the configuration, we at least have the option to backwards support previously saved config files. Should we use Dioptas version? Or should we have a separate version for configuration files?

**Comment by CPrescher** [comment]
I am almost done with merging.
What I do not understand, why do you need a temp folder? 
Why do the images and the masks need to be saved there?

**Comment by erangre** [comment]
I need the temp folder for the image in case the image does not exist when the user opens the saved configuration on a new computer.
For the mask it is in case the user makes changes to the mask, is not happy with them, so instead of reloading the saved configuration, has the option to load the mask from the temp directory. Maybe it is not so important.

**Comment by CPrescher** [comment]
but the image is anyway saved in the configuration. Why is there a need to have it as a file?
In case somebody really wants this, they still save it, but I do not see many usecases...

**Comment by erangre** [comment]
Regarding the image, if everything works without the need to save it, then there is no need to save it. I thought I had to have an actual saved image somewhere for it to function properly, because it shows which file is open. Perhaps I was even relying on it in the code.

**Comment by CPrescher** [comment]
Ok, I refactored a lot. Temporary folder is now not needed anymore. 
Further, I changed the code so that Dioptas saves a complete model (including several configurations).

Do you have any use case where it would be better to only save 1 configuration? If not I would add save and load buttons at the left side and use those as general buttons (for multiple configurations also).

I think I will also make it so that Dioptas saves its state each time it closes so we can load the saved state on restart, maybe there also needs to be an auto save every 10 minutes or so. If Dioptas crashes on the beamline this should help a lot, since it should be very easy to recover phases and overlays etc.

**Comment by erangre** [comment]
Regarding saving one configuration. I did it that way since if you have something already open in one configuration, you might want to open a previous project as another configuration and continue working on both.

An autosave would be great, but I think on reopening Dioptas (crash or no crash) it should ask if you want to reload the previous project.

**Comment by CPrescher** [comment]
Hm, but this really include also loading several overlays and phases from the other configuration? Strictily speaking a configuration only holds the image information and the calibration geometry (at least how it is defined right now in Dioptas). If you only want an extra configuration for some different analysis but keep the same phases and overlays i think it is not needed to be saved (just load image and calibration).

**Comment by erangre** [comment]
I see. Then such a feature as I described would actually work better as an "append project" feature. It would still save all configurations and load all configurations, without replacing the existing ones, and while appending phases and overlays. (possibly asking which configurations should be loaded out of the project). But this is not an urgent feature. Just something to think about for the future.

**Comment by CPrescher** [comment]
yes, there is many things which can be done :).
I would make it as a whole Dioptas Project save right now, since this is very useful for people actually working with several detectors (like at LCLS) and then we can think about adding additional features.

One drawback of the saving in hdf5 is that it is hard to make executables using hdf5, at least I was not able to repeat my success from last week...

**Pull request merged**
