### PR TITLE
Few fixes

### PR DESCRIPTION
**Pull request by karnevskiy**
This MR contains mostly fixes.

There is a new feature: background roi shown on BatchView.

### CODE REVIEW

**Comment by CPrescher** [comment]
thanks!

**Comment by CPrescher** [comment]
Could you write a list of changes for the pull request, which we could add to the changelog?

**Comment by karnevskiy** [comment]
Full list of changes are given by the commit messages. I add a short summary in the description of the pull request.

**Comment by CPrescher** [comment]
Hi, the changelog is basically for non-technical and do not know the code. Good would be the distinction of "new features" and "bug fixes", so that it is clear for everybody who uses Dioptas what changed. 

Thank you!

**Pull request merged**
