### PR TITLE
remove remainders of python2 compatibility

### PR DESCRIPTION
**Pull request by a-detiste**
python3-future is being removed from Debian these days

### CODE REVIEW

**Comment by a-detiste** [comment]
ping ...

**Comment by CPrescher** [comment]
pong

**Comment by a-detiste** [comment]
Indenpendtly of this issue I cannot get 0.5.9 to build

```
pyx because it changed.
[1/1] Cythonizing dioptas/model/util/smooth_bruckner_cython.pyx
[02/12/24 07:25:03] WARNING  pyproject.toml does not contain a tool.setuptools_scm section                                                                                   setuptools.py:119
I: pybuild plugin_pyproject:144: Unpacking wheel built for python3.12 with "installer" module
E: pybuild pybuild:391: build: plugin pyproject failed with: expected str, bytes or os.PathLike object, not NoneType
I: pybuild plugin_pyproject:129: Building wheel for python3.11 with "build" module
I: pybuild base:305: python3.11 -m build --skip-dependency-check --no-isolation --wheel --outdir /home/tchet/deb/dioptas/.pybuild/cpython3_3.11_dioptas  
[02/12/24 07:25:31] WARNING  pyproject.toml does not contain a tool.setuptools_scm section                                                                                   setuptools.py:119
I: pybuild plugin_pyproject:144: Unpacking wheel built for python3.11 with "installer" module
E: pybuild pybuild:391: build: plugin pyproject failed with: expected str, bytes or os.PathLike object, not NoneType
dh_auto_build: error: pybuild --build -i python{version} -p "3.12 3.11" returned exit code 13
```

**Comment by CPrescher** [comment]
hi,

i am looking into the future thing right now. Could you create a separate issue for the build problem. I have never used pybuild, I am currently using poetry build, but i guess pybuild just calls poetry?

**Comment by a-detiste** [comment]
>  I guess pybuild just calls poetry?

Too much or too little magic. I don't know, lots of heuristics. It can be forced.

**Pull request merged**
