### PR TITLE
Calibrant pattern lines set to appear in place when calibration is run in other unit

### PR DESCRIPTION
**Pull request by erangre**
Modified the Calibration Controller.
Previously if the unit in the integration tab was set to Q or d, and then a calibration was performed in the calibration tab, the lines in the pattern appeared out of place since they were getting 2theta values, whereas the integrated spectrum was showing up in the new unit.
Now the lines are calculated to the new unit and the x axis label changes according to the new unit.

### CODE REVIEW

**Comment by erangre** [comment]
Added another change:
Previously, when switching integration units, the pattern background would not update properly (since the values of the linear region item were not updated). Now they values are updated, and the smooth width is updated to keep the shape of the background similar as well. This works well for transitions between 2theta and Q, but it still does not help the case of d units.

**Comment by erangre** [comment]
Fixed some problems with the modifications to the calibration controller (enabling pattern view with other units):
When the program was started, if no wavelength or unit is set, there was an error. Now if they are not set, it uses the default values.

Formatted P and T to 2 decimal points (there was a problem that when adding small increments to the P or T values, then even with a double precision float, eventually there are round-off errors, and the legend would show a very long number).

Added the option to save patterns as GSAS fxye.

**Comment by CPrescher** [comment]
This Pull Request has a lot of different things, which are kind of colliding with the current code...

Could you make a smaller PR for the intended changes to the calibration controller only?

**Comment by erangre** [comment]
Sure, I will work on this once I finish with the configurations.

**Comment by erangre** [comment]
Looks like the changes to the calibration controller were already implemented in a separate pull request and I just forgot to close this pull request.
There are a few small changes here that I need to make separate pull requests for, but nothing urgent.

**Pull request closed without merging**
