### PR TITLE
Compute histogram(log(data)) rather than log(histogram(data))

### PR DESCRIPTION
**Pull request by t20100**
This PR is a prototype to illustrate the proposition from #144 to compute the histogram on log(data).

Doing so, the computed bins are equally spaced in the display of the histogram, and it deals better with huge values used to fill the gaps.

Screenshots with [CeO2_Pilatus1M.tif](https://github.com/Dioptas/Dioptas/blob/develop/dioptas/tests/data/CeO2_Pilatus1M.tif):
- Current (most of the pixels falls in the first bin): dioptas-CeO2
- With this PR: dioptas-log-hist-CeO2

Screenshots with an image from Eiger ID27@ESRF:
- Current (only 2 non-empty bins: first and last): dioptas-eiger
- With this PR: dioptas-log-hist-eiger

There is still a few things to consider/check, especially the impact on computing the auto_levels which is based on the histogram and how to retrieve the image data.

Let me know if this is of interest and I'll continue working on it.

related to #144

### CODE REVIEW

**Comment by CPrescher** [comment]
I tested it several kind of images and I think it works well. Would you want to change anything else (currently still a draft) or can I merge?

**Comment by t20100** [comment]
I'd prefer to have a second look at it before you merge it.

**Comment by t20100** [comment]
This PR affects the `auto_level` computation since the stored histogram (`hist_x`, `hist_y`) no longer has equally spaced bins, so the computed bounds are slightly different (though the visual result looks to be the same for most of the image I tried).

It's used here:
- https://github.com/Dioptas/Dioptas/blob/83a020177d01609850a02215f5830c1689e519e9/dioptas/widgets/plot_widgets/ImgWidget.py#L136-L137
- https://github.com/Dioptas/Dioptas/blob/83a020177d01609850a02215f5830c1689e519e9/dioptas/widgets/plot_widgets/HistogramLUTItem.py#L306-L310

If you prefer to keep the previous behavior, I can update this PR to compute twice the histogram:
- once with equally spaced bin edges for the auto_level computation.
- once with log space for the display.

**Comment by CPrescher** [comment]
The new behavior is good. Thank you!

**Pull request merged**
