### PR TITLE
Alternate view mode

### PR DESCRIPTION
**Pull request by CPrescher**
See how this looks

### CODE REVIEW

**Comment by erangre** [comment]
I got some feedback asking to have labels of Overlay and Phase when in alternate view mode.

**Comment by CPrescher** [comment]
Ok, what exactly do. you mein by Labels?

**Comment by erangre** [comment]
Something similar to what you have in the Calibration Tab:
For instance, you have a box with a label (or header, or caption, not sure how to call it) "Start values" and one with "Peak Selection" etc...

**Comment by CPrescher** [comment]
is this pull request still up to date, or did you change anything?

**Comment by erangre** [comment]
We discussed about making some changes to it. I haven't done it yet, so we should wait with it.

**Comment by CPrescher** [comment]
OK

**Comment by erangre** [comment]
I think it is better now.

**Comment by CPrescher** [comment]
Looks good so far. The only thing which seems to not work, is dock and undock. Doing this adds the image on top again. I tried to find where to fix it, but could not so far...

**Comment by CPrescher** [comment]
I really have a hard time understanding all the flags in conjunction with the change_gui_view function.

Would it be possible to refactor, by have a function "switch_to_normal_view" and "switch_to_alernative_view"?

and then not use several boolean flags but rather a string, describing the current state?

**Comment by erangre** [comment]
I didn't want to change the flags to strings because it would mean I can't use "not" for switching states.
I gave the flags cleared names now, and created separate functions for the change_view_mode so it should be clearer now.

**Comment by CPrescher** [comment]
hmm, a bit better. But I still do not understand why you need the bool variables
"is_docked_in_alternative_gui_view" and "is_undocked_in_alternative_gui_view"
shouldn't they always be exactly the opposite of each other?

Wouldn't it be better to have a bool variable for img_docked (already available)
and one for the view state. Something like: self.is_in_alternative_view

and then each case can be easily asked:
if img_docked and alternative:
 ....

etc.

**Comment by erangre** [comment]
I guess I didn't make it clear why I need both.
One is for the docked state and one is for the undocked state.
The default for docked state is the normal view (False)
And the default for the undocked state is alternative view (True).
But in principle someone might want to have it always in normal view, even if it is undocked, so this way if they switch from docked to undocked it can remember their preference for using normal or alternative view. And someone else might prefer to have it always in alternative view.

**Comment by CPrescher** [comment]
Hm, I actually did not before realize that undock also changed the view. Now, I understand the approach a better. However, I actually think that undock should only undock the image and "change view" should change the orientation. 
Why does "undock" need to do both? Do you have the use-case, that people switch around very often? If not, I would prefer the variant, that each button does only one thing. I think that this is usually more clear to the user.

**Comment by erangre** [comment]
The main reason is that I think the default should be that when you undock that it also changes view because otherwise you have a lot of empty space.
But I do see that people have different tastes:
1. some people prefer to have the pattern as wide as possible on the screen so they never want to use the alternative view.
2. Some people prefer to always have the phases and overlays visible so they always use alternative view.
3. Some people go back and forth between duck and undock, so that when they are looking at the image they want it undocked, but when it is cake they want it docked so they can see the pattern and the cake in line with each other.
4. Some people prefer to have it in the alternative view only when undocked, because both image and pattern are smaller in the alternative view. People do switch often between dock and undock in this case, especially when they have other windows open (like jcpds editor, or map) or some other software open.

**Comment by CPrescher** [comment]
I agree with the space issue. But I still think one button should do only one thing. Especially only the thing it states.

What we could do, if the image is undocked and there is enough space we could also add the pattern and phase control on top as extra panels... (in case there is only space for two panels, one could have one on the right side for either pattern or phase)

I anyway need to shorten the different panels a bit soon. this would also benefit the alternate view mode by having less space taken by the right side....

What would you think about this?

**Comment by erangre** [comment]
I don't mind if we change it to one button per action.
Maybe the best option is to have icons for different possible views, so that it is not a change view button.
Regarding adding the pattern and phase controls above the pattern, there seems to be enough space for this even when you don't undock.

**Comment by CPrescher** [comment]
Ok, I will merge it and simplify it.

**Pull request merged**
