### PR TITLE
Masking arcs

### PR DESCRIPTION
**Pull request by erangre**
This modification allows masking arcs.
Also modified the other mask shapes to start out with a QPointF and not a QPoint.

### CODE REVIEW

**Comment by erangre** [comment]
I noticed that for some reason there are also changes in the calibration controller, probably I branched this from the wrong branch and it was already there.

**Comment by CPrescher** [comment]
Can you try to revert the one commit where the change in calibration controller has been done?

**Comment by erangre** [comment]
I couldn't find that commit in the list of commits in my branch, so I couldn't revert. Instead I ran a comparison to a branch without it and undid those changes and made a new commit.

**Comment by CPrescher** [comment]
I like it a lot. Thanks for it!

**Comment by erangre** [comment]
The only problem is, that similar to Polygon it has these rough edges (I think because of a change in pyqtgraph, but maybe it was something else)

**Comment by CPrescher** [comment]
I just fixed this in 675a5d21a187daa7d79d9adc5317e9c1a93d5e1e
i think this was due to a change in PyQT (changing from version 4 to 5)

**Comment by erangre** [comment]
perfect!

**Pull request merged**
