### PR TITLE
Add axes to image

### PR DESCRIPTION
**Pull request by erangre**
Added bottom and left axes to image.
For cake mode there should be a way to have the horizontal axis be in Q (or 2theta) and the vertical in azimuthal angle. However, using the pyqtgraph axis I found no way of setting the range manually and keep it linked to the image (it is possible to change the scale, but then there is no shift). Perhaps the only way to do this is to manually set it and then when the scale of the image changes to have a signal update the range of the axes appropriately.

### CODE REVIEW

**Comment by CPrescher** [comment]
Hm, the code looks good. I do not know yet if I like it. It kind of destroys my aesthetics...

Why do we need axes for the image? Do we really need to show pixel values on axes? If you really want to know pixel value of a peak you anyway have to look on the mouse cursor position.

I agree that it adds a lot of information for the cake view, maybe only having axes in cakeview? Or somehow make it as an option?

The cakeview axes actually also should change based on the integration unit selected...

Best wishes,
Clemens

**Comment by erangre** [comment]
Having the axes in pixels in not important actually. And it will look better without it,.
I wasn't sure how to make it change units also, especially with "d" units.

**Comment by erangre** [comment]
I see that there are conflicts now. Probably since I haven't updated this branch to all the other commits. Should I merge the other commits into it first?

**Comment by CPrescher** [comment]
Merged.

Now also the axes change with the slider and I changed the slider to be in the center by default...

**Pull request merged**
