### PR TITLE
CI: use conda-forge and lightsource2 packages

### PR DESCRIPTION
**Pull request by CJ-Wright**
Get packages from conda rather than pip.

### CODE REVIEW

**Comment by CPrescher** [comment]
I think this is a great idea. I did not know about conda-forge. (only here pyfai is missing in the list and dateutil is only for python 2) 

I already tested a modified version on another branch.

**Comment by CJ-Wright** [comment]
pyFAI is on [conda-forge](https://github.com/conda-forge/pyfai-feedstock)

**Comment by CJ-Wright** [comment]
as is [pyqtgraph](https://github.com/conda-forge/pyqtgraph-feedstock)

**Comment by CJ-Wright** [comment]
as is [pycifrw](https://github.com/conda-forge/pycifrw-feedstock) with python 2.7 support. If there is an issue with the conda-forge build of pycifrw please let the maintainers know so that it can be fixed (full disclosure I am one of the maintainers).

**Comment by CPrescher** [comment]
thx, i only meant that pyfai was missing from your pull request...

i have to check pyqtgraph, because i think i did have a bugfix which was not in the main repository...

**Comment by CJ-Wright** [comment]
pyepics is also on conda under the `lightsource2` channel.

**Comment by CPrescher** [comment]
i have seen, but pyfai is not working for python 3.6 yet, right?

**Comment by CPrescher** [comment]
does your pcifrw work for python 2.7 and 3.5?

**Comment by CJ-Wright** [comment]
pycifrw has 2.7, 3.5, and 3.6 support

**Comment by CJ-Wright** [comment]
We will support 3.6 on pyFAI [soon](https://github.com/conda-forge/pyfai-feedstock/issues/7), although you should feel free to add to that issue (PRs are also welcome).

**Comment by CPrescher** [comment]
ok, great. 
I actually made python 2.7 and python 3.5 travis tests passing again.
using the conda-forge rep makes everything much smoother, thanks for maintaining those packages...

I will also change Readme, for easier installation

**Comment by CJ-Wright** [comment]
No problem!
I'm glad they are being used and are useful. When I get some more time I may be able to put this on conda-forge too! (If you are interested).

**Comment by CPrescher** [comment]
yes, certainly.
But it should be related to the latest tag here in github (which is 3.1), correct?

I always wanted to release a new version, but this will probably take some more time....

**Comment by CJ-Wright** [comment]
Yes usually we go off of tagged releases, rather than bleeding edge code.

**Pull request closed without merging**
